# Generated by Django 5.0.4 on 2024-05-11 10:49

import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_on',
            new_name='modified_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='idx',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_obsolete',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
