# Generated by Django 5.0.4 on 2024-05-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fathers_name',
            new_name='father_name',
        ),
    ]
