# Generated by Django 5.0.4 on 2024-06-02 11:27

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autho', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255)),
                ('pan_num', models.CharField(blank=True, max_length=9, null=True)),
                ('vat_num', models.CharField(blank=True, max_length=9, null=True)),
                ('permanent_add', models.CharField(max_length=255)),
                ('pan_registration_date', models.DateField(blank=True, null=True)),
                ('pan_registration_place', models.CharField(blank=True, max_length=100, null=True)),
                ('lone_taker_type', models.CharField(choices=[('personal', 'Personal'), ('company', 'Company')], default='company', max_length=10)),
                ('profiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.JSONField(default=dict)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cooperative.finance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlacklistReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('progress', 'Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='progress', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_list_reports', to='autho.user')),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_list_reports', to='cooperative.finance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('category', models.CharField(choices=[('borrower', 'Borrower'), ('guarantor', 'Guarantor')], default='borrower', max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('blacklisted', 'Blacklisted'), ('relished', 'Relished')], default='blacklisted', max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('report_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_list', to='autho.user')),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_list', to='cooperative.finance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='cooperative.finance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('reason', models.CharField(max_length=500)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='cooperative.finance')),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='autho.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_due_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_outstanding', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('good', 'Good'), ('watchlist', 'Watchlist'), ('pass', 'Pass'), ('npl', 'Npl'), ('doubtful', 'Doubtful'), ('bad debt', 'Bad debt')], default='good', max_length=20)),
                ('loan_nature', models.CharField(choices=[('term', 'Term'), ('overdraft', 'Overdraft')], default='term', max_length=20)),
                ('is_closed', models.BooleanField(default=False)),
                ('utilization_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maturity_date', models.DateField()),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='cooperative.finance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='autho.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField()),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_outstanding', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='cooperative.loanaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='cooperative.finance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='autho.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_guarantors', to='cooperative.loanaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autho.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('type', models.CharField(choices=[('real state', 'Real state'), ('fixed asset', 'Fixed asset'), ('higher purchase', 'Higher purchase')], default='real state', max_length=20)),
                ('description', models.TextField()),
                ('ownership_type', models.CharField(choices=[('own', 'Own'), ('third party', 'Third party')], default='own', max_length=20)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nature_of_charge', models.CharField(default='first_charge', editable=False, max_length=20)),
                ('latest_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('latest_valuation_date', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='cooperative.loanaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(db_index=True, default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_holders', to='cooperative.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autho.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
