# Generated by Django 5.0.4 on 2024-06-16 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquirer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='cooperative.financestaff'),
        ),
    ]
